env:
  listPublishDirectory: Website
  pathToCi: ci
name: Build on push to feature branch for testing
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - '*'
      - '!main'
  push:
    branches:
      - '*'
      - '!main'
permissions:
  contents: read
jobs:
  build:
    name: Build the page
    uses: ./.github/workflows/build-common.yml
