env:
  listPublishDirectory: Website
  pathToCi: ci
name: Build on push to feature branch for testing
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - '*'
      - '!main'
  push:
    branches:
      - '*'
      - '!main'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
  build:
    name: Build the page
    uses: ./.github/workflows/build-common.yml
