concurrency:
  cancel-in-progress: true
  group: pages
env:
  listPublishDirectory: Website
  pathToCi: ci
name: Build Repo Listing
on:
  push:
    branches:
      - main
    paths:
      - source.json
  repository_dispatch:
  workflow_dispatch:
permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  id-token: write
  pages: write
jobs:
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Check out the automation repository
        uses: actions/checkout@v4
        with:
          clean: false # otherwise the local repo will no longer be checked out
          path: ${{ env.pathToCi }}
          repository: vrchat-community/package-list-action
      - name: Deploy the global.json file
        run: cp "${{ github.workspace }}/global.json" "${{ env.pathToCi }}/"
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          path: |
            ${{ env.pathToCi }}/.nuke/temp
            ~/.nuget/packages
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Build Package Version Listing
        run: '"${{ env.pathToCi }}/build.cmd" BuildMultiPackageListing --root "${{ env.pathToCi }}" --list-publish-directory "$GITHUB_WORKSPACE/${{ env.listPublishDirectory }}"'
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.listPublishDirectory }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
