name: Build on push to feature branch for testing
on:
  push:
    branches:
      - '*'
      - '!main'
permissions:
  contents: read
env:
  listPublishDirectory: Website
  pathToCi: ci
jobs:
  build:
    name: Build the page
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Check out the automation repository
        uses: actions/checkout@v4
        with:
          repository: vrchat-community/package-list-action
          path: ${{ env.pathToCi }}
          clean: false # otherwise the local repo will no longer be checked out
      - name: Deploy the global.json file
        run: cp "${{ github.workspace }}/global.json" "${{ env.pathToCi }}/"
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.pathToCi }}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Build Package Version Listing
        run: '"${{ env.pathToCi }}/build.cmd" BuildMultiPackageListing --root "${{ env.pathToCi }}" --list-publish-directory "$GITHUB_WORKSPACE/${{ env.listPublishDirectory }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
